### ISSUE TITLE
建议像端点星那样添加版权说明

### ISSUE THREAD

**Issue by chinatimeline** [DamoresClub/DamoresClub.github.io#1]
某些boilerplate还是必要的

**Comment by chinatimeline** [comment]
https://github.com/Terminus2049/Terminus2049.github.io/blob/master/_layouts/post.html

```html
  <hr style="border-top:1px solid #28323C;"/>

  <font size=2px>
	   <p>评论请前往 <a href="https://2049bbs.xyz/">2049BBS.xyz</a>（<span style="color:red">已被墙</span>）</p>
  </font>

	<div class="social-share" data-disabled="linkedin,diandian,tencent,facebook"></div>

  <font size=2px><span style="color:red">
    本站已被屏蔽</span>，分享到墙内时请转本文的 GitHub 原始页面 <a href="https://github.com/Terminus2049/Terminus2049.github.io/blob/master/{{ page.path }}">{{ page.title }}</a>，或者查看可直连的镜像 <a href="{{ site.baseurl }}/about.html">网站</a>。
    <br>
    文章版权归原作者所有。此处收录仅供存档研究，不代表本站立场。
  </font>

  <script> pangu.spacingPage(); </script>
```

**Comment by DamoresClub** [comment]
> https://github.com/Terminus2049/Terminus2049.github.io/blob/master/_layouts/post.html
> 
> ```
>   <hr style="border-top:1px solid #28323C;"/>
> 
>   <font size=2px>
> 	   <p>评论请前往 <a href="https://2049bbs.xyz/">2049BBS.xyz</a>（<span style="color:red">已被墙</span>）</p>
>   </font>
> 
> 	<div class="social-share" data-disabled="linkedin,diandian,tencent,facebook"></div>
> 
>   <font size=2px><span style="color:red">
>     本站已被屏蔽</span>，分享到墙内时请转本文的 GitHub 原始页面 <a href="https://github.com/Terminus2049/Terminus2049.github.io/blob/master/{{ page.path }}">{{ page.title }}</a>，或者查看可直连的镜像 <a href="{{ site.baseurl }}/about.html">网站</a>。
>     <br>
>     文章版权归原作者所有。此处收录仅供存档研究，不代表本站立场。
>   </font>
> 
>   <script> pangu.spacingPage(); </script>
> ```

好建议，我考虑一下措辞，稍后加上

**Comment by DamoresClub** [comment]
已添加。
